2024-06-24T13:30:15 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1719235815.364733, "uuid": "108963a4b8e145acb146072f8fa4044b"}
2024-06-24T13:30:26 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235826.465356, "uuid": "b0d5f49b04374de092c9df693be71d1d"}
2024-06-24T13:30:26 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235826.466737, "uuid": "30ae90d5288d4dc7acfc42eb30218eb9"}
2024-06-24T13:30:30 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235830.792129, "uuid": "739b34e5f32d4b08804207af3a32a385"}
2024-06-24T13:30:30 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235830.793128, "uuid": "e354ed7456e74070882fabaf8cd164fa"}
2024-06-24T13:30:55 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235855.165107, "uuid": "d89212e9f8f24a6299bc2172bfd1cf93"}
2024-06-24T13:30:55 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235855.166532, "uuid": "097f482000b1444c867397e87d7fb1ac"}
2024-06-24T13:31:08 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235868.272684, "uuid": "ea4ebe1b89f44c46ac9a0e8eff37aa5f"}
2024-06-24T13:31:08 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235868.273791, "uuid": "d8bc10c060844784be6e8891c157221f"}
2024-06-24T13:31:20 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235880.59238, "uuid": "56b9c00942eb430a979fb2ce6b299a50"}
2024-06-24T13:31:20 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235880.59356, "uuid": "914034eb373d456183c504a5babbcc2b"}
2024-06-24T13:31:23 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235883.502891, "uuid": "225685467264426889bacd58861e3072"}
2024-06-24T13:31:23 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235883.503977, "uuid": "5e1d04d5fafe4ae096f22d6be64af3cf"}
2024-06-24T13:31:30 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235890.958427, "uuid": "386cde558a7949fd85ca3ed3344b8db8"}
2024-06-24T13:31:30 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235890.959587, "uuid": "5a77a5542ffd4843a6a3052f45531c88"}
2024-06-24T13:31:35 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235895.081358, "uuid": "7d1dbe0805fa4eddac2573ac49bea080"}
2024-06-24T13:31:35 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235895.08241, "uuid": "6c46d7f4beb1472b98659e5e6462acd4"}
2024-06-24T13:31:39 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235899.820767, "uuid": "41b5bf776a82478394b29509357172d5"}
2024-06-24T13:31:39 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235899.821837, "uuid": "9e1a583738184ed4b2d5ba599a857733"}
2024-06-24T13:31:40 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235900.178409, "uuid": "68ef21ff97b74336bdbd971f13cdedfb"}
2024-06-24T13:31:40 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235900.179498, "uuid": "f260dd7349064c10892194294a0de399"}
2024-06-24T13:31:45 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235905.552107, "uuid": "aefc3de7d0a44decb4088c080a801ef0"}
2024-06-24T13:31:45 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235905.553063, "uuid": "b1fec9c7cb3f42238b24bf605e00d78c"}
2024-06-24T13:31:54 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235914.56153, "uuid": "8e2c564301374fbd895e9f413a84f7af"}
2024-06-24T13:31:54 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235914.562538, "uuid": "509e85761f1847fe9cb2d7bbe2e67461"}
2024-06-24T13:31:56 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235916.026977, "uuid": "c15e9d7fea51411cb3a9af918fc293e8"}
2024-06-24T13:31:56 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235916.027979, "uuid": "8d9eebf1c49f4b3f9a8eb3f64d3f3063"}
2024-06-24T13:31:57 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235917.777911, "uuid": "03ff1427a86e49b49343d7fe6d581a4e"}
2024-06-24T13:31:57 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235917.779113, "uuid": "b16b3cfdb65749abbe733a1e42239276"}
2024-06-24T13:31:59 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "list index out of range", "timestamp": 1719235919.426503, "uuid": "bca5e5de877f4ce2ac7a1027bcfe1644"}
2024-06-24T13:31:59 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "INFO", "message": "Glasgow Central Station", "timestamp": 1719235919.427529, "uuid": "bad4f88c4f1f4765ad26643671a98521"}
2024-06-24T13:32:04 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "WARNING", "message": "Exception thrown when attempting to run <function BlockExecutor.execute.<locals>.__execute_with_retry at 0x7f4a10718f70>, attempt 1 of 1", "timestamp": 1719235924.923879, "uuid": "c9b6cb8e357c457ea5aa0791ea914c58", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1185, in _execute\n    self.block.run_tests(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 3329, in run_tests\n    test_function(*outputs)\n  File \"<string>\", line 117, in test_output\nNameError: name 'df' is not defined\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 787, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 46, in retry_func\n    logger.warning(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 39, in warning\n    self.__send_message('warning', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["name 'df' is not defined"]}
2024-06-24T13:32:04 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "block_type": "transformer", "level": "EXCEPTION", "message": "Failed to execute block rentflow_gmap_data_integration", "timestamp": 1719235924.92984, "uuid": "b81d1b4a8d224c019bf95c9b1824498b", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1185, in _execute\n    self.block.run_tests(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 3329, in run_tests\n    test_function(*outputs)\n  File \"<string>\", line 117, in test_output\nNameError: name 'df' is not defined\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 787, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 649, in execute\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["name 'df' is not defined"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1185, in _execute
    self.block.run_tests(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 3329, in run_tests
    test_function(*outputs)
  File "<string>", line 117, in test_output
NameError: name 'df' is not defined
