2024-06-24T13:29:46 {"cpu": 0.0048828125, "cpu_total": 16, "cpu_usage": 0.00030517578125, "memory": 2980.0, "memory_total": 9582.0, "memory_usage": 0.31099979127530786, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235786.367997, "uuid": "533d148c5d9b4aaeb29760a1a4e2efaa"}
2024-06-24T13:29:46 {"cpu": 0.0048828125, "cpu_total": 16, "cpu_usage": 0.00030517578125, "memory": 3003.0, "memory_total": 9582.0, "memory_usage": 0.31340012523481525, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235786.598834, "uuid": "df72d766d447498da7c07facbbea501d"}
2024-06-24T13:29:46 {"block_run_id": 13, "block_uuid": "ingest_data_from_csv", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Execute PipelineRun 5, BlockRun 13: pipeline home_rent_etl_pipeline block ingest_data_from_csv", "timestamp": 1719235786.683292, "uuid": "b3b9ed14ab444a5893c80c4aad568cb3"}
2024-06-24T13:29:47 {"block_run_id": 13, "block_uuid": "ingest_data_from_csv", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "BlockRun 13 (block_uuid: ingest_data_from_csv) completes.", "timestamp": 1719235787.216411, "uuid": "3f4cc685572d4525aea796eaff28a054"}
2024-06-24T13:29:55 {"cpu": 0.00390625, "cpu_total": 16, "cpu_usage": 0.000244140625, "memory": 3015.0, "memory_total": 9582.0, "memory_usage": 0.31465247338760177, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235795.753054, "uuid": "953ddc840726404295bca7c1d64b97af"}
2024-06-24T13:29:55 {"block_run_id": 14, "block_uuid": "rentflo_data_transformer", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Execute PipelineRun 5, BlockRun 14: pipeline home_rent_etl_pipeline block rentflo_data_transformer", "timestamp": 1719235795.898429, "uuid": "d5a8392175ce4c18ba63e05d724b4067"}
2024-06-24T13:29:56 {"block_run_id": 14, "block_uuid": "rentflo_data_transformer", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "BlockRun 14 (block_uuid: rentflo_data_transformer) completes.", "timestamp": 1719235796.442738, "uuid": "fa2be10d6ef64161aa5847a9bcabe955"}
2024-06-24T13:30:05 {"cpu": 0.0029296875, "cpu_total": 16, "cpu_usage": 0.00018310546875, "memory": 3006.0, "memory_total": 9582.0, "memory_usage": 0.3137132122730119, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235805.959984, "uuid": "fe4119fe9b974967a6042e2be2d2af86"}
2024-06-24T13:30:15 {"cpu": 0.001953125, "cpu_total": 16, "cpu_usage": 0.0001220703125, "memory": 2980.0, "memory_total": 9582.0, "memory_usage": 0.31099979127530786, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235815.151756, "uuid": "701cbd6d18a342e3b373d16272bb4ef2"}
2024-06-24T13:30:15 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Execute PipelineRun 5, BlockRun 15: pipeline home_rent_etl_pipeline block rentflow_gmap_data_integration", "timestamp": 1719235815.346015, "uuid": "0a1ba510fd8d4ef5acef35e3019815e9"}
2024-06-24T13:30:25 {"cpu": 0.0009765625, "cpu_total": 16, "cpu_usage": 6.103515625e-05, "memory": 3089.0, "memory_total": 9582.0, "memory_usage": 0.3223752869964517, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235825.378997, "uuid": "a83367a1a91743b2b7212332eeae9130"}
2024-06-24T13:30:35 {"cpu": 0.0, "cpu_total": 16, "cpu_usage": 0.0, "memory": 3093.0, "memory_total": 9582.0, "memory_usage": 0.3227927363807138, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235835.531654, "uuid": "a8a651b31e894ce4a12b5c48b310b097"}
2024-06-24T13:30:45 {"cpu": 0.0, "cpu_total": 16, "cpu_usage": 0.0, "memory": 3091.0, "memory_total": 9582.0, "memory_usage": 0.32258401168858275, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235845.687635, "uuid": "b55ac9b18a8146df965093775dcfff75"}
2024-06-24T13:30:55 {"cpu": 0.0, "cpu_total": 16, "cpu_usage": 0.0, "memory": 3092.0, "memory_total": 9582.0, "memory_usage": 0.3226883740346483, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235855.840546, "uuid": "e8f3aba8c05e462fb6a696913ad4d605"}
2024-06-24T13:31:05 {"cpu": 0.0, "cpu_total": 16, "cpu_usage": 0.0, "memory": 3096.0, "memory_total": 9582.0, "memory_usage": 0.3231058234189105, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235865.991061, "uuid": "b3e360e690614c2f967d41421dddf824"}
2024-06-24T13:31:15 {"cpu": 0.0, "cpu_total": 16, "cpu_usage": 0.0, "memory": 3100.0, "memory_total": 9582.0, "memory_usage": 0.3235232728031726, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235875.136145, "uuid": "9aa9dd61861e40ef97d8576aa3a87516"}
2024-06-24T13:31:25 {"cpu": 0.00537109375, "cpu_total": 16, "cpu_usage": 0.000335693359375, "memory": 3104.0, "memory_total": 9582.0, "memory_usage": 0.32394072218743475, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235885.263055, "uuid": "c235802f539d4b32b7afb26c48b23ed1"}
2024-06-24T13:31:35 {"cpu": 0.00439453125, "cpu_total": 16, "cpu_usage": 0.000274658203125, "memory": 3106.0, "memory_total": 9582.0, "memory_usage": 0.3241494468795659, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235895.390788, "uuid": "7bf5edd696e544c18559f7c9207855d6"}
2024-06-24T13:31:45 {"cpu": 0.00341796875, "cpu_total": 16, "cpu_usage": 0.000213623046875, "memory": 3106.0, "memory_total": 9582.0, "memory_usage": 0.3241494468795659, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235905.520046, "uuid": "51cdcc67e88f4ed6b3d0c7659bc9eb23"}
2024-06-24T13:31:55 {"cpu": 0.00244140625, "cpu_total": 16, "cpu_usage": 0.000152587890625, "memory": 3107.0, "memory_total": 9582.0, "memory_usage": 0.3242538092256314, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235915.674447, "uuid": "8f75377dc86746689ceb612744d04cda"}
2024-06-24T13:32:05 {"block_run_id": 15, "block_uuid": "rentflow_gmap_data_integration", "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "EXCEPTION", "message": "BlockRun 15 (block_uuid: rentflow_gmap_data_integration) failed.", "timestamp": 1719235925.631472, "uuid": "c9e5d3d103aa4c15ad1943cc2cd61606", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1185, in _execute\n    self.block.run_tests(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 3329, in run_tests\n    test_function(*outputs)\n  File \"<string>\", line 117, in test_output\nNameError: name 'df' is not defined\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 787, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 465, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["name 'df' is not defined"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1185, in _execute
    self.block.run_tests(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 3329, in run_tests
    test_function(*outputs)
  File "<string>", line 117, in test_output
NameError: name 'df' is not defined
2024-06-24T13:32:05 {"cpu": 0.00146484375, "cpu_total": 16, "cpu_usage": 9.1552734375e-05, "memory": 3009.0, "memory_total": 9582.0, "memory_usage": 0.3140262993112085, "pipeline_run_id": 5, "pipeline_schedule_id": 2, "pipeline_uuid": "home_rent_etl_pipeline", "hostname": "8239930deddd", "level": "INFO", "message": "Pipeline home_rent_etl_pipeline for run 5 in schedule 2 is alive.", "timestamp": 1719235925.82077, "uuid": "1830876ae05e41458aa04a9d52bfdb40"}
